name: haj_repairs_sign_in
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0-265.0.dev

dependencies:
  intl: ^0.18.1
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.0
  flutter_appauth: ^6.0.0
  encrypt: ^5.0.1
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.1.0
  http: ^1.2.0
  mobile_scanner: ^3.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/haj-logo.png
    - assets/haj-reception.json